# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install shared libs
      run: sudo apt-get install -y --no-install-recommends libpoppler-glib-dev
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    # - name: Build with pdfium
    #   run: go build -tags nomsgpack,pdfium .
    - name: Build with poppler
      run: go build -tags nomsgpack,poppler .

