name: Release Artefacts
on:
  push: 
    tags: "v*"
env:
  GOFLAGS: "-trimpath -ldflags=-w -buildmode=pie"
  GOARM64: v8.0
  GOAMD64: v2
  GOEXPERIMENT: jsonv2
jobs:
  compile-linux:
    name: Build glibc Linux Release Artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Install cross-compiling tools
        run: sudo apt-get install -y -q binutils-aarch64-linux-gnu
      - name: Compile TES for Linux and Windows, arm64 and amd64
        run: |
          mkdir dist
          # empty default for linux
          export ext=''
          for GOOS in windows linux; do
            if test "${GOOS}" = windows ; then
              ext='.exe'
            else
              ext=''
            fi
            for GOARCH in amd64 arm64; do
              # PDFium embedded
              exe="dist/tes-pdfium-${GOOS}-${GOARCH}${ext}"
              GOOS="${GOOS}" GOARCH="${GOARCH}" pkg/pdflibwrappers/pdfium_purego/download-pdfium.sh
              GOOS="${GOOS}" GOARCH="${GOARCH}" go build -o "${exe}" -tags=embed_pdfium
              file "${exe}"
              # no PDFium embedded
              exe="dist/tes-${GOOS}-${GOARCH}${ext}"
              GOOS="${GOOS}" GOARCH="${GOARCH}" go build -o "${exe}"
              file ${exe}
            done
          done
          ls -lah ./dist/
      - name: Save GNU Linux and Windows Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: "tes-linux-window-pdfium-embedded"
          path: ./dist/*
  compile-musl-linux:
    name: Build Musl libc Linux Artifacts
    runs-on: ubuntu-latest
    container: golang:alpine
    steps:
      - name: Install tools
        run: apk update && apk add file binutils binutils-aarch64
      - uses: actions/checkout@v5
      - name: Build arm64 and amd64 Musl Linux binaries
        run: |
          mkdir dist
          for GOARCH in amd64 arm64; do
            exe="dist/tes-pdfium-musl-linux-${GOARCH}"
            GOARCH=$GOARCH pkg/pdflibwrappers/pdfium_purego/download-pdfium.sh
            GOARCH=$GOARCH go build -o "${exe}" -tags=embed_pdfium
            # no PDFium embedded
            exe="dist/tes-musl-linux-${GOARCH}"
            GOARCH=$GOARCH go build -o "${exe}"
            file "${exe}"
          done
          ls -lah dist/
      - name: Save Musl Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "tes-musl-linux-pdfium-embedded"
          path: ./dist/*
  compile-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Build for Darwin on arm64 and amd64
        run: |
          mkdir dist
          for GOARCH in amd64 arm64; do
            exe="dist/tes-pdfium-mac-${GOARCH}"
            GOARCH=$GOARCH pkg/pdflibwrappers/pdfium_purego/download-pdfium.sh
            GOARCH=$GOARCH go build -o "${exe}" -tags=embed_pdfium
            file "${exe}"
            # no PDFium embedded
            exe="dist/tes-mac-${GOARCH}"
            GOARCH=$GOARCH go build -o "${exe}"
          done
          ls -lah dist/
      - name: Save Darwin Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "tes-darwin-pdfium-embedded"
          path: ./dist/*
  create-release:
    runs-on: ubuntu-latest
    needs: 
      - compile-darwin
      - compile-linux
      - compile-musl-linux
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with: 
          merge-multiple: true
      - name: Compress artifacts
        run: |
          ls -lah
          gzip *
          sha256sum * > sha256sum.txt
          ls -lah && du -h .
      - name: Create Release draft
        uses: ncipollo/release-action@v1
        with:
          draft: true
          omitBody: true
          artifacts: "*"
